apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 654654241329.dkr.ecr.us-east-1.amazonaws.com/innovatech-spa-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80