name: CD - Deploy a ECS

on:
  workflow_run:
    workflows: ["CI - Build y Push a ECR"]
    types:
      - completed
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: innovatech-spa-cluster

jobs:
  deploy:
    name: Deploy a ECS
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Frontend
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service innovatech-spa-frontend-service \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy Backend Ventas
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service innovatech-spa-backend-ventas-service \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deploy Backend Despacho
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service innovatech-spa-backend-despacho-service \
            --force-new-deployment \
            --region $AWS_REGION
