name: CI - Build y Push a ECR

on:
  push:
    branches:
      - main
      - develop

env:
  AWS_REGION: us-east-1
  ECR_URL: 654654241329.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Frontend
        working-directory: front_despacho
        run: |
          docker build -t $ECR_URL/innovatech-spa-frontend:${{ github.sha }} .
          docker tag $ECR_URL/innovatech-spa-frontend:${{ github.sha }} $ECR_URL/innovatech-spa-frontend:latest
          docker push $ECR_URL/innovatech-spa-frontend:${{ github.sha }}
          docker push $ECR_URL/innovatech-spa-frontend:latest

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Backend Ventas
        working-directory: backend/Springboot-API-REST-VENTAS
        run: |
          docker build -t $ECR_URL/innovatech-spa-backend:${{ github.sha }} .
          docker tag $ECR_URL/innovatech-spa-backend:${{ github.sha }} $ECR_URL/innovatech-spa-backend:latest
          docker push $ECR_URL/innovatech-spa-backend:${{ github.sha }}
          docker push $ECR_URL/innovatech-spa-backend:latest

      - name: Build y Push Backend Despacho
        working-directory: backend/Springboot-API-REST-DESPACHO
        run: |
          docker build -t $ECR_URL/innovatech-spa-backend:${{ github.sha }} .
          docker tag $ECR_URL/innovatech-spa-backend:${{ github.sha }} $ECR_URL/innovatech-spa-backend:latest
          docker push $ECR_URL/innovatech-spa-backend:${{ github.sha }}
          docker push $ECR_URL/innovatech-spa-backend:latest